name: Run tests

on: [ push ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        working-directory: ./backend
        run: npm install
      - name: Run tests
        working-directory: ./backend
        run: npm test
      - name: Upload JUnit Test Report
        uses: actions/upload-artifact@v3
        with:
          name: jest-junit-backend-report
          path: ./backend/reports/jest-junit.xml
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        working-directory: ./frontend
        run: npm install
      - name: Run tests
        working-directory: ./frontend
        run: npm test

